### ISSUE TITLE
✨ Generated GitHub workflow files: Inherit GitHub secrets by default

### ISSUE THREAD

**Issue by ckunki** [exasol/python-toolbox#162]
## Observed behavior 

I had some trouble to run integration tests in my CI build, which required using GitHub secrets for accessing an Exasol SaaS database instance, see [saas-api-python](https://github.com/exasol/saas-api-python).

Some of the GitHub workflows generated by the PTB use the trigger `workflow_call`.
In this case, secrets are not inherited by default. 

## Proposed Fix 

Update file `.github/workflows/ci.yml` generated by PTB and add 

```yaml
  ci-job:
    name: Checks
    uses: ./.github/workflows/checks.yml
    secrets: inherit
```

If you have security concerns, then we could add this as a comment and add some documentation.
