### ISSUE TITLE
🔧 Pin All Docker Images in GitHub Actions Workflows

### ISSUE THREAD

**Issue by Nicoretti** [exasol/python-toolbox#344]
## Summary

Pin all used Docker images in GitHub Actions workflows to specific image versions for the provided templates as well as the workflows for the repository itself.

## Background & Context

Locking Docker images to specific versions ensures that the execution environment remains consistent and reproducible. This is especially important in the context of automatic updates or changes applied to the `:latest` image tags by GitHub or Docker Hub. By pinning the images, we can avoid unexpected breaking changes and maintain a stable CI/CD pipeline.

## Example

**Before:**

```yaml
...
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        ...
```

**After:**

```yaml
...
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
        ...
```
## References:

- [Runners](https://docs.github.com/en/actions/using-github-hosted-runners/using-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories)
- [GitHub Actions Documentation](https://docs.github.com/en/actions)
