### ISSUE TITLE
🔧 Pin PTB Runners (OS version) in GitHub Actions Workflows

### ISSUE THREAD

**Issue by ArBridgeman** [exasol/python-toolbox#388]
## Summary

Pin all used Docker images in the PTB GitHub Actions workflows to specific image versions for the provided templates as well as the workflows for the repository itself.

## Example

**Before:**

```yaml
...
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        ...
```

**After:**

```yaml
...
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
        ...
```
