### ISSUE TITLE
📝 Make regular execution of CI build optional

### ISSUE THREAD

**Issue by ckunki** [exasol/python-toolbox#424]
Current PTB generates GitHub workflow files including instructions to run the CI build regularly each week:

```yaml
schedule:
    # "At 00:00 on every 7th day-of-month from 1 through 31." (https://crontab.guru/)
    - cron: "0 0 1/7 * *"
```

Many projects do not need this feature, it can also be detrimental 
* waste computing resources 
* create unexpected failures
* create unexpected costs

The current ticket therefore requests to 
* either make this feature optional
* disable it by default, e.g. by commenting it
